servicename: sc-telemetry
stages:
  udp:
    poolconfig:
      autoscale: true
      initialworkers: 1
      minworkers: 1
      maxworkers: 8
      queuedepthperworker: 128
      scaledownfactor: 0.1
      scaledownbackoff: 1.5
      autoscaleinterval: 3s
    ipaddr: 127.0.0.1
    port: 20000
  cannelloni:
    poolconfig:
      autoscale: true
      initialworkers: 1
      minworkers: 1
      maxworkers: 8
      queuedepthperworker: 128
      scaledownfactor: 0.1
      scaledownbackoff: 1.5
      autoscaleinterval: 3s
    robconfig:
      outputchannelsize: 256
      maxseqnum: 255
      primarybuffersize: 128
      auxiliarybuffersize: 128
      flushtreshold: 0.3
      basealpha: 0.2
      jumpthreshold: 8
    robtimeout: 50ms
  can:
    poolconfig:
      autoscale: true
      initialworkers: 1
      minworkers: 1
      maxworkers: 8
      queuedepthperworker: 128
      scaledownfactor: 0.1
      scaledownbackoff: 1.5
      autoscaleinterval: 3s
    messages: []
  questdb:
    poolconfig:
      autoscale: true
      initialworkers: 1
      minworkers: 1
      maxworkers: 8
      queuedepthperworker: 128
      scaledownfactor: 0.1
      scaledownbackoff: 1.5
      autoscaleinterval: 3s
    address: localhost:9000
connectors:
  udpsize: 4096
  cannellonisize: 4096
  canSize: 4096
dbcfilepath: /app/can/db.dbc
